### ISSUE TITLE
ProtocolLib 5.0.0, SessionLogin(AuthMe) and AuthMeBungee bug.

### ISSUE THREAD

**Issue by ColorsASD** [AuthMe/AuthMeBungee#112]
Hi. The "session" and "AuthMeBungee" do not work correctly with the new "ProtocolLib v5.0.0".

After SessionLogin, AuthMeBungee still thinks the player is not logged in.

Until this is resolved, I went back to 4.8.0, but soon I have a 1.19 server update, but without it, I'm bleeding because of the function.

So please fix it. <3

**Comment by chelminski** [comment]
I have the same problem. I'm joining the thread and waiting for an update

**Comment by ColorsASD** [comment]
> I have the same problem. I'm joining the thread and waiting for an update

I don't have this error anymore:
AuthMeBungee-v2.2.0-b206.jar
AuthMe-v5.6.0-b2599.jar
ProtocolLib-v5.0.0-b636.jar
