### ISSUE TITLE
Saving the last position of the player on the server on which he was last before leaving the server

### ISSUE THREAD

**Issue by DarkFort** [AuthMe/AuthMeBungee#14]
Suppose there are two survival servers, the player was last on one server and left. Then he went in and returned it to the same server. The same function is present in the plugin "BungeeAuth by yooxa"

**Comment by hex3l** [comment]
@sgdc3 AuthMe shouldn't do that by default?

**Comment by sgdc3** [comment]
Just use different location columns per server. Please ask for help on the AuthMeReloaded page.
