### ISSUE TITLE
AutoLogin doesn't work

### ISSUE THREAD

**Issue by flechabenx** [AuthMe/AuthMeBungee#15]
I have the autologin option enabled in AuthMeBungee config and I have two servers. The idea is that players login in the "lobby" server and then they can go to survival server without login again. Currently, this is my config (I enabled bungeecord option in AuthMe in both servers):

![1](https://user-images.githubusercontent.com/6844371/34420412-932e4c86-ebf0-11e7-9336-2c1396a8ddcc.png)

But when I enter the survival server after login in the lobby server, AuthMe send two messages: "This user isn't registerd" and "Please, register to the server with.....". Also in the console says:
"[AuthMe] The user Ajneb has been automatically logged in, as requested by the AuthMeBungee integration."

It says that I am already logged in but still tell me to register :/

I tried setting just the "lobby server" on authServers in AuthMeBungee config, but still doesn't work.

**Comment by sgdc3** [comment]
please post your authmereloaded config file

**Comment by flechabenx** [comment]
Ok here is it. Is the same config for lobby and survival server
https://pastebin.com/hwpmhTb4

**Comment by sgdc3** [comment]
You have to use a common mysql database

**Comment by flechabenx** [comment]
Thank you, now it works!
