### ISSUE TITLE
hack my server

### ISSUE THREAD

**Issue by ghost** [AuthMe/AuthMeBungee#17]
any one player can join ( without login ) to my admin account

then can use any bungee command, example.
`/server`
or
`/end`

---

i must remove this permission
`/lp group lider permission set bungeecord.* false`

---

authme bungee config
```
# List of servers which required to be authenticated
serversList:
  - hub
  - s2-survival
# Allows or not commands to be performed if user is not logged in
commandsRequiresAuth: true
# List of commands allowed to be perform without being authenticated
commandsWhitelist:
  - /glist
# Allows or not user to talk in chat if he is not logged in
chatRequiresAuth: true
# Kick all players who switch servers without being authenticated (eg. plugin teleport)
# Do not set this option to true unless you know what you're doing!
serverSwitchRequiresAuth: false
# Enable session resume between servers (eg. autologin if you change server)
autoLogin: true
```

authme bungee
`https://ci.xephi.fr/job/AuthMeBungee/34/`

authme
`https://ci.xephi.fr/job/AuthMeReloaded/1892/`

**Comment by sgdc3** [comment]
please describe your network structure

**Comment by ghost** [comment]
@sgdc3 

timings - hub
`https://timings.aikar.co/?id=96dbb0db1f1b4fadb483f8f853e61f51`

travertine - bungee
`https://ci.lucko.me/job/Travertine/`

plugins - bungee
```
SkinsRestorer-v13.1.3.jar
ServerListPlus-3.4.7-Universal.jar
LuckPerms-Bungee-4.0.10.jar
BungeeTabListPlus-2.8.3-SNAPSHOT.jar
BungeeChat-2.1.6.855.jar
bungeeban-2.6.7.jar
BungeeAliases-1.1.4.jar
authmebungee-2.0.1-SNAPSHOT.jar
```

you can join to my server

<details>

`mc.dragonsonline.pl`

</details>

**Comment by sgdc3** [comment]
I mean the servers structure: lobbies, auth servers, minigames, etc... In which servers do you have authme installed?

**Comment by ghost** [comment]
any other server in my network has doesn't matter.

**Comment by sgdc3** [comment]
you need to put into the list any server that is running authmereloaded

**Comment by ghost** [comment]
ok. i disabled all of my servers without bungee and hub. hacker still can hack my server

example. hacker join ( without login ) on my account to server and use `/end` command
sarver has down! so easy. you can fix this? very please.

**Comment by sgdc3** [comment]
Please, post your bungee config (remove ip and ports) Also include your hub spigot.yml and your authme config.yml (remove mysql credentials)

**Comment by ghost** [comment]
> Also include your hub spigot.yml

see in timings
`https://timings.aikar.co/?id=96dbb0db1f1b4fadb483f8f853e61f51#config`

bungee config
```
https://gist.github.com/KonoromiHimaries/c0cff2a1dedf16270993cb2330bb1f96
```

authme config
```
https://gist.github.com/KonoromiHimaries/7a09f161ba894a9c6b2c603ae4579b61
```

**Comment by sgdc3** [comment]
Server list is case sensitive, you need to call it Hub not hub @KonoromiHimaries

**Comment by ghost** [comment]
it's work, thx : D
