### ISSUE TITLE
May I translate the introduction of this plugin to mcbbs？

### ISSUE THREAD

**Issue by ExerciseBook** [AuthMe/AuthMeBungee#23]
With a lots of people asked me about how to share the login session through the server under a bungeecord. I want to thanslate the introduction of this plugin to mcbbs.net . 
Before my translation may I take your permission?

**Comment by sgdc3** [comment]
We are under GPL3 license: https://github.com/AuthMe/AuthMeBungee/blob/master/LICENSE

**Comment by sgdc3** [comment]
What do you mean with "translate the introduction"?

**Comment by sgdc3** [comment]
the documentation?

**Comment by ExerciseBook** [comment]
the way to use.

**Comment by sgdc3** [comment]
sure, maybe link the original wiki/documentation also ;)

**Comment by ExerciseBook** [comment]
Maybe @polarcn will translate it. 
加油，如果你(polarcn)没空的话我再帮你翻译吧。
我在到高考之前，只有五一有时间了。

**Comment by polarcn** [comment]
我在五一期间搞定吧，如果你想占坑的话那也没关系咯*。٩(ˊωˋ*)و✧

**Comment by ExerciseBook** [comment]
虽然好久没在mcbbs~~水~~发过贴了，我很想占。
但是我两年多没碰过mcserver了。。貌似有点悬，还是您翻译吧。 我也没时间去捣鼓。您去弄吧！ 

加油！回头给你回帖点并评分。
