### ISSUE TITLE
Chat problem

### ISSUE THREAD

**Issue by DarkFort** [AuthMe/AuthMeBungee#28]
After the last update of the plugin, it became impossible to write anything to the chat, neither the command nor the message.

**Comment by DarkFort** [comment]
Sorry, it's my fault.

**Comment by sgdc3** [comment]
@JH3Y50N please stop advertising your plugin here, AuthMeBungee is the only official bungeecord addon.

**Comment by DarkFort** [comment]
Now all is well, simply, the server specified the server Survival because of this and did not write anything in the chat.
![image](https://user-images.githubusercontent.com/25278617/44807394-22cad480-abd2-11e8-8b16-e51000234c03.png)
