### ISSUE TITLE
require login again after switch

### ISSUE THREAD

**Issue by sadoj-kuro** [AuthMe/AuthMeBungee#30]
I have 2 server or according to works very well however with my server in 1.13.1 it asks again to login.
i have setting server correcly and adding in config of plugin bungee

Authmereloaded: 5.5.0
Authmebungee: 2.0.2 (Maybe need a update plugin for working with 5.5.0 ?)
i have testing authmebungee 2.1.0 (dev build) with authmeReload 5.5.0 and dont working 

authme config: https://hastebin.com/xosapazofa.bash
bridge config: https://hastebin.com/rahedomate.bash

working fine ont Authme server and Survie server but not in Dev server in 1.13.1

**Comment by sgdc3** [comment]
You have to use the latest authmebungee build

**Comment by sadoj-kuro** [comment]
Tested with 2.1.0 and 5.5.0 not working

**Comment by sgdc3** [comment]
This one? https://ci.codemc.org/job/AuthMe/job/AuthMeBungee/

**Comment by sgdc3** [comment]
Use both latest builds of both AuthMeBungee and AuthMeReloaded (https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/)

**Comment by sadoj-kuro** [comment]
yes and yes using lasted version of AuthMeBungee and AuthMeReloaded  with codemc link 

dont working

**Comment by sgdc3** [comment]
@KuroSenseii I tested it on a test environment, i wasn't able to reproduce your issue, could you share the plugin list?

**Comment by Mario359** [comment]
I have the same issue with AuthMe 5.5 build:2138 with PaperSpigot 1.13.1 and BungeeCord
I have enabled bungeecord in the configuration, and I use MySQL as a database for all servers
A player told me about an error message the very first time he switched
But nothing in the console at this time, no more information
Before I used FastLogin, but sometimes it made players invincible when switching (The plugin does not support 1.13)

**Comment by sgdc3** [comment]
@Mario359 which authmebungee version are you using?

**Comment by Mario359** [comment]
Actually AuthMe 5.5 #2149 on all Paper 1.13.2 servers and AuthMe-Bungee 2.1 #83 for BungeeCord
AuthMe-Bungee configuration:
```

# List of servers which required to be authenticated
authServers: 
- '1'
- '2'
- '3'
- '4'
commands:
    # Allows or not commands to be performed if user is not logged in
    requireAuth: true
    # List of commands allowed to be perform without being authenticated
    whitelist: 
    - '/login'
    - '/register'
    - '/l'
    - '/reg'
    - '/email'
    - '/captcha'
# Allows or not user to talk in chat if he is not logged in
chatRequiresAuth: true
serverSwitch:
    # Kick all players who switch servers without being authenticated (eg. plugin teleport)
    requiresAuth: false
    kickMessage: 'Vous devez vous connecter'
# Enable auto-login between servers
autoLogin: true
# If enabled, unlogged users will be sent to the unloggedUserServer server!
sendOnLogout: false
# If sendOnLogout is enabled, unlogged users will be sent to this server!
unloggedUserServer: ''

**Comment by sgdc3** [comment]
@KuroSenseii did you manage to fix the issue?
