### ISSUE TITLE
Send the player to the lobby even if the password is wrong during login.

### ISSUE THREAD

**Issue by Cubey03** [AuthMe/AuthMeBungee#32]
I investigated all day to find the solution to this problem but nothing, so I came to the conclusion that it is an AuthMe Bug. If you type "/ login <random password> (ex. / Login nutellahdjdjdhjs)" while your password is 'sweatshirt', you will be teleported to the server you chose when the player should be sent after login

**Comment by krusic22** [comment]
What version (Bungee, AuthMe, AuthMeBungee, Spigot) are you using?
Do you have multiple lobbys?
Do you use MySQL?
Do you use sessions?
And did you try disabling caching?

**Comment by Cubey03** [comment]
I'm using AuthMe 5.4.0 on a PaperSpigot server. I have one lobby server. I don't use MySQL and Yes, I'm using sessions. I haven't tried to disabling chaching.

**Comment by sgdc3** [comment]
Please download tge latest builds of AuthMe and AuthMeBungee, try disabling caching or using mysql instead of sqlite.

**Comment by sgdc3** [comment]
@Cubey03 any news?
