### ISSUE TITLE
Clients 1.6 and below issue

### ISSUE THREAD

**Issue by Lachney** [AuthMe/AuthMeBungee#35]
Using ProtocolSupport and ProtocolSupportBungee. (This plugin supports clients from 1.4.7 - 1.13.2)
Using latest versions of AuthMe and AuthMeBungee. Using MySQL and Caching disabled. If you are a client on 1.6 and below, you are authenticated (if it does it for you automatically) however, you can't chat or use any commands still and it doesn't teleport you to servers. I'm not sure if you'll fix this issue or not since it is for super outdated clients but if you do, you're awesome. <3

Edit: One little work around you could do right now with the current builds is when they authenticate to use the bungee send command to send them to the lobby and everything works from there lol

**Comment by krusic22** [comment]
Does it work for 1.13.x users?

**Comment by Lachney** [comment]
It sure does :P
@krusic22

**Comment by SliderKP** [comment]
use 5.4.0 authme dev and work for now... im not 100% sure if u server are secure S: im with the same problem.

**Comment by sgdc3** [comment]
@Lachney any news?

**Comment by Lachney** [comment]
> 
> 
> @Lachney any news?

Hey there, I did some testing with the latest builds... I wanted to let you know that AuthMe was working correctly with older clients connecting to a 1.13.2 server with ProtocolSupport... I didn't test it with AuthMeBungee. But I noticed when switching servers on 1.6 and below with bungee and protocolsupport gives you a End of Stream error, I don't believe it's nothing to do with AuthMe at all so don't worry.  If you want to, you can close this issue for now.

I am going to do some more testing later when I am up for it.  Thanks for checking back on this issue, it is highly appreciated.
