### ISSUE TITLE
Problem ProtocolSupport?

### ISSUE THREAD

**Issue by SliderKP** [AuthMe/AuthMeBungee#37]
SAME PROBLEM THEN https://github.com/AuthMe/AuthMeBungee/issues/35

Bungee + AuthMeBungee 
Spigot + AuthMe-5.5.1-SNAPSHOT.jar + Protocol Support

Users CANT move and use commands, works in Authme 5.4.0 but im not 100% sure if my server is secure!

**Comment by sgdc3** [comment]
Duplicated
