### ISSUE TITLE
AuthMe does not connect with AuthMeBungee

### ISSUE THREAD

**Issue by Leodragon08** [AuthMe/AuthMeBungee#52]
I Follow this guide:

Download AuthMeBungee package
Place AuthMeBungee.jar into your BungeeCord's plugin folder
MAKE SURE THAT hooks.bungeecord is enabled in your authme (spigot side) config file!
Restart everything
Configure the plugin (don't forget to edit the configuration file)
Enjoy!

I have 2 problems:

1. I can't find the hooks.bungeecord string, I find this:

# Do we need to hook with BungeeCord?
    bungeecord: true

2. Despite having put Hook with Bungeecord: true it doesn't work. It makes me log in but it doesn't let me write or change servers or make commands.

Use Authme 5.6.0

Sorry for my bad English.

Goodbye.

**Comment by krusic22** [comment]
Make sure to use the latest AuthMe and AuthMeBungee builds from Jenkins/Build server.

**Comment by Leodragon08** [comment]
> Make sure to use the latest AuthMe and AuthMeBungee builds from Jenkins/Build server.

Now I download the files from Jenkins.

**Comment by Leodragon08** [comment]
> Make sure to use the latest AuthMe and AuthMeBungee builds from Jenkins/Build server.

I downloaded the files from Jenkins but they are not detected? The config is not created.

**Comment by Leodragon08** [comment]
I fix, thanks.

**Comment by draand28** [comment]
How did you fix it?
