### ISSUE TITLE
Access to Privileged BungeeCord Commands

### ISSUE THREAD

**Issue by bundabrg** [AuthMe/AuthMeBungee#54]
If `requireAuth` is `false` then a player can log in with another player and access privileged bungeecord instructions (IE, `glist`) without needing to log in.

This is prevented by setting `requireAuth` to `true` but now players with no registered accounts can't do anything outside the whitelist. I could update the whitelist with every command an unauth player is likely to need but that has other issues.

What I'd like is the following:
  * If a player has an account, limit what they can access unauthenticated to the whitelist. Admins will require registered accounts.
  * If a player has no account, then they have access to all commands that their user has permission to (They're treated as quasi logged in). This falls back to normal permission system which should be limited.

Perhaps an additional flag: `commands.whitelistRequiresAccount` default to `true` to preserve backwards compatibility. If `false` then the whitelist will be ignored if the player has no registered account.

## Reproducing

  * Log in as a user with access to a privileged command and an account with `requireAuth: false`. Easiest to test is the Bungeecord `glist` command
  * Without logging in, execute the command. It works.
  * Now set `requireAuth: true` and log in with a user without an account. Will not be able to commands outside of whitelist like `/help` etc. 

Once again, probably expected behaviour but I don't want to force users to create an account and I have about 26 backend vanilla servers all with lots of commands particular to them.

**Comment by sgdc3** [comment]
The issue should be handled spigot-side
