### ISSUE TITLE
AuthmeBungee didn't realized if I logined and blocked me from talking or commands

### ISSUE THREAD

**Issue by Untitled** [AuthMe/AuthMeBungee#62]
I did all I see in readme, put this plugin into bungeecord plugins/ and my authme was installed on 'lobby' server.
I changed config.yml of AUTHME: Hook.bungeecord=true.
when I tried to login, I succeeded but I couldn't talk or use commands.It just looked like that AuthmeBungee thinks I didn't login.
How can I fix this problem?I tried many times fixing config.yml for Authme and AuthmeBungee,but it seems not working. Help me please, many thanks.

**Comment by Untitled** [comment]
[configs.zip](https://github.com/AuthMe/AuthMeBungee/files/4534591/configs.zip)
config.yml of AuthmeBungee and Authme

**Comment by Untitled** [comment]
`
# List of servers which required to be authenticated
authServers: 
- 'lobby'
commands:
    # Allows or not commands to be performed if user is not logged in
    requireAuth: true
    # List of commands allowed to be perform without being authenticated
    whitelist: 
    - '/login'
    - '/register'
    - '/l'
    - '/reg'
    - '/email'
    - '/captcha'
# Allows or not user to talk in chat if he is not logged in
chatRequiresAuth: true
serverSwitch:
    # Kick all players who switch servers without being authenticated (eg. plugin teleport)
    requiresAuth: true
    kickMessage: 'Authentication required.'
# Enable auto-login between servers
autoLogin: false
# If enabled, unlogged users will be sent to the unloggedUserServer server!
sendOnLogout: true
# If sendOnLogout is enabled, unlogged users will be sent to this server!
unloggedUserServer: 'lobby'`
config.yml of AuthmeBungee

**Comment by 8bitFra** [comment]
Did you solve the problem?

**Comment by sgdc3** [comment]
Fixed in the latest authme dev builds
