### ISSUE TITLE
AuthMeBungee doesn't block commands / autologin doesn't work

### ISSUE THREAD

**Issue by Bloedarend** [AuthMe/AuthMeBungee#63]
I'm using Waterfall and Paper Spigot, and these are the versions of AuthMe that I use:
- AuthMeBungee 2.2.0 SNAPSHOT
- AuthMeReloaded 5.6.0 SNAPSHOT. 

My spigot server named 'auth' has the AuthMeReloaded plugin. So I edited the config on bungeecord to this:
`# List of servers which required to auth servers`
`authServers:`
`- auth`
I have also enabled `requireAuth: true` and `autoLogin: true`. 

When setting up AuthMeReloaded, I couldn't find hooks.bungeecord anywhere in the config. What I did find was this:
`# Do we need to hook with BungeeCord`
`bungeecord: true`
I assume this is the same thing, so I guess I've enabled hooks.bungeecord.

But, whenever I join the server on my account I can run commands like `/lpb editor` without having to login first. And when I go to the hub server, then later connect back to the auth server, I will have to login again, even though autologin is enabled. 

I've asked for support on the Discord support server, but they don't seem to know what's wrong. And neither do I, because it should be working. If anyone could help me, please reply below. 

List of plugins I'm using:

**Bungeecord:**
- AuthMeBungee
- CMI
- CleanMotD
- FastLogin
- LuckPerms-Bungee

**Spigot:**
- AuthMe
- AutoRestart
- CMI
- FastLogin
- LuckPerms-Bukkit
- PlaceholderAPI
- ProtocolLib
- ProtocolSupport
- TAB
- Vault
- Viaversion
- bAnnouncer

**Comment by WilliamEstrela** [comment]
I have the same problem, have you solved it?

**Comment by Bloedarend** [comment]
Nope, still waiting for support :/

**Comment by AntiRemedy** [comment]
I had the same problem, it is related to Paper Spigot. I avoid the bug by using an older version of it. I have tested multiple versions and one that works with autologin between servers is build 212. So you could use that instead of the latest one. You could also use the latest version of normal Spigot.

**Comment by Bloedarend** [comment]
> I had the same problem, it is related to Paper Spigot. I avoid the bug by using an older version of it. I have tested multiple versions and one that works with autologin between servers is build 212. So you could use that instead of the latest one. You could also use the latest version of normal Spigot.

I'm assuming you're using Paper Spigot 1.15.2? Because I'm currently using 1.12.2 Paper Spigot, which is build 1618. I don't really want to switch to the regular Spigot, so do you by any chance, know if there's a way to get this to work on 1.12.2?

**Comment by Bloedarend** [comment]
Also tried setting up my server with paper for 1.15.2, just using luckperms and AuthMeReloaded, and I could still use bungeecord commands while not authenticated.

**Comment by AntiRemedy** [comment]
> > I had the same problem, it is related to Paper Spigot. I avoid the bug by using an older version of it. I have tested multiple versions and one that works with autologin between servers is build 212. So you could use that instead of the latest one. You could also use the latest version of normal Spigot.
> 
> I'm assuming you're using Paper Spigot 1.15.2? Because I'm currently using 1.12.2 Paper Spigot, which is build 1618. I don't really want to switch to the regular Spigot, so do you by any chance, know if there's a way to get this to work on 1.12.2?

Yes, I'm using Paper 1.15.2. But I just tested the version you are using and it works with just Protocollib, AuthMe and AuthMeBungee. Which versions of Waterfall, AuthMeBungee 2.2.0 SNAPSHOT and AuthMeReloaded 5.6.0 SNAPSHOT are you using exactly? I used the latest development builds of each.

**Comment by luwdev-br** [comment]
I'm having problems with "auto-login" too, any prediction of when this error will be fixed? :(

**Comment by kekke3r** [comment]
I am experiencing this issue too, for now i'm keeping a older version of Paper to keep the auto-login working.

**Comment by luwdev-br** [comment]
> I am experiencing this issue too, for now i'm keeping a older version of Paper to keep the auto-login working.

which version are you using?

**Comment by Sylensky** [comment]
This server is running Paper version git-Paper-201 (MC: 1.15.2) 
- This one works for me.

**Comment by kekke3r** [comment]
I'm still on Paper Build 196 1.15.2

**Comment by fsosaaa** [comment]
already solved?

**Comment by Asgardia23** [comment]
the problem still persists. tried everything. doesnt work.

**Comment by yashendra2797** [comment]
Any idea what's going on?

**Comment by arturek1666** [comment]
Same issue here :(

**Comment by cicatrice74** [comment]
You need to use Protocolsupport to solve this issue until it is fixed by developer

**Comment by Sylensky** [comment]
i just tested it with paper-378 and it is valid. so i guess some protocols get lost in the latest paper builds or in authme.

**Comment by Misterio77** [comment]
Same issue, Paper-131 1.16.1

**Comment by africsnail** [comment]
Same issue on my paper 1.16.1 server.
Running latest devbuilds of both Authme and Authmebungee. 

Had this issue since some build of paper 1.15.2

**Comment by wallxq** [comment]
Please update this for autologin.

**Comment by wallxq** [comment]
When was update for autologin?

**Comment by wallxq** [comment]
When will be the update?

**Comment by zSteley** [comment]
same problem, please fix autologin

**Comment by bobhenl** [comment]
8 months...

**Comment by filasik** [comment]
so what?

**Comment by gbrxxl** [comment]
Has anyone the solution to the problem?

**Comment by arturek1666** [comment]
Nope :(, it fills like devs who worked on authme has disappeared, as no updates for 2 months now

**Comment by maxspeed3006** [comment]
Issue seems to be fixed: https://github.com/AuthMe/AuthMeReloaded/commit/b1e9b432944ecef98e0c08685bb23154f2cebb77

Just downloaded the latest AuthMe snapshot and autologin works.

**Comment by filasik** [comment]
Thanks for info, ill try 😊 S pozdravem,Filip Škeřík Od: maxspeed3006Odesláno:středa 17. března 2021 15:52Komu: AuthMe/AuthMeBungeeKopie: Filip Skerik; CommentPředmět: Re: [AuthMe/AuthMeBungee] AuthMeBungee doesn't block commands / autologin doesn't work (#63) Issue seems to be fixed: ***@***.***Just downloaded latest AuthMe snapshot and autologin works.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by arturek1666** [comment]
Finally :)
